faf-client:
  server:
    host: 31.135.14.173
    port: 8001

  irc:
    host: 31.135.14.173
    port: 6697

  vault:
    base-url: https://content.faforever.com
    replay-download-url-format: http://31.135.14.173:81/replays/0/0/0/0/%s.fafreplay

  news:
    feed-url: https://direct.faforever.com/news/feed

  replay:
    remote-host: 31.135.14.173
    remote-port: 15000

  website:
    base-url: https://www.faforever.com

  api:
    base-url: http://31.135.14.173:8010
    client-id: 3bc8282c-7730-11e5-8bcf-feff819cdc9f
    client-secret: 6035bd78-7730-11e5-8bcf-feff819cdc9f

  oauth:
    base-url: https://hydra.faforever.ru
    scopes: openid offline public_profile upload_map upload_mod lobby
    client-id: faf-java-client
    redirect-uri: http://localhost:53037

  forged-alliance:
    exe-url: https://content.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe

  use-remote-preferences: false
