faf-client:
  server:
    host: host.faforever.ru
    port: 8001

  irc:
    host: host.faforever.ru
    port: 6697

  vault:
    max-file-size-mb: ${MAX_FILE_SIZE_MB:50}
    base-url: https://content.faforever.ru
    replay-download-url-format: https://content.faforever.ru/replays/%s.fafreplay
    static-message-first: Моды создаются и добавляются простыми игроками, поэтому некоторые моды или их комбинации, могут приводить к крашу игры.
    static-message-second: Из рекомендованных администрацией модов Advanced target priorities и Supreme score board  (научитесь ими пользоваться).

  news:
    feed-url: https://direct.faforever.ru/news/feed

  replay:
    remote-host: host.faforever.ru
    remote-port: 15000

  website:
    base-url: https://www.faforever.ru

  api:
    base-url: https://api.faforever.ru
    client-id: 3bc8282c-7730-11e5-8bcf-feff819cdc9f
    client-secret: 6035bd78-7730-11e5-8bcf-feff819cdc9f

  oauth:
    base-url: https://hydra.faforever.ru
    scopes: openid offline public_profile upload_map upload_mod lobby
    client-id: faf-java-client
    redirect-uri: http://localhost:53037

  forged-alliance:
    exe-url: https://content.faforever.ru/faf/updaterNew/updates_faf_files/ForgedAlliance.exe

  use-remote-preferences: false
